import { ExampleItem } from "./types";

// Keep it small but varied; we will tile/repeat to fill background.
export const SEED_EXAMPLES: ExampleItem[] = [
  // WORLD
  {
    id: "w-1",
    kind: "Abstimmung",
    topics: ["Klima", "Wirtschaft"],
    topics_en: ["Climate", "Economy"],
    title_de: "Soll ein globaler CO2-Mindestpreis gelten?",
    title_en: "Should a global minimum CO2 price apply?",
    scope: "WORLD",
  },
  {
    id: "w-2",
    kind: "Debattenpunkt",
    topics: ["Medien", "Digitales"],
    topics_en: ["Media", "Digital"],
    title_de: "Wie begrenzen wir Desinformation, ohne Meinungsfreiheit zu gefährden?",
    title_en: "How do we limit disinformation without endangering freedom of speech?",
    scope: "WORLD",
  },
  {
    id: "w-3",
    kind: "Debattenpunkt",
    topics: ["Umwelt"],
    topics_en: ["Environment"],
    title_de: "Wie schützen wir Meere wirksam vor Plastikmüll?",
    title_en: "How do we effectively protect oceans from plastic waste?",
    scope: "WORLD",
  },
  {
    id: "w-4",
    kind: "Abstimmung",
    topics: ["Klima", "Gerechtigkeit"],
    topics_en: ["Climate", "Justice"],
    title_de: "Soll es einen globalen Fonds für Klimaschäden geben?",
    title_en: "Should there be a global fund for climate damages?",
    scope: "WORLD",
  },
  {
    id: "w-5",
    kind: "Debattenpunkt",
    topics: ["Gesundheit", "Humanitär"],
    topics_en: ["Health", "Humanitarian"],
    title_de: "Wie sichern wir globale Impfstoffgerechtigkeit in Krisen?",
    title_en: "How do we ensure global vaccine fairness in crises?",
    scope: "WORLD",
  },
  {
    id: "w-6",
    kind: "Abstimmung",
    topics: ["Digitales", "Wahlen"],
    topics_en: ["Digital", "Elections"],
    title_de: "Soll es weltweite Regeln für digitale Wahlwerbung geben?",
    title_en: "Should there be global rules for digital election advertising?",
    scope: "WORLD",
  },
  {
    id: "w-7",
    kind: "Debattenpunkt",
    topics: ["Arbeit", "Wirtschaft"],
    topics_en: ["Work", "Economy"],
    title_de: "Wie verhindern wir Kinderarbeit in globalen Lieferketten wirksam?",
    title_en: "How do we effectively prevent child labor in global supply chains?",
    scope: "WORLD",
  },

  // EU
  {
    id: "eu-1",
    kind: "Debattenpunkt",
    topics: ["Migration"],
    topics_en: ["Migration"],
    title_de: "Wie wird Migration EU-weit fair und praktikabel geregelt?",
    title_en: "How can migration be managed across the EU in a fair and practical way?",
    scope: "EU",
  },
  {
    id: "eu-2",
    kind: "Abstimmung",
    topics: ["Wirtschaft"],
    topics_en: ["Economy"],
    title_de: "Brauchen wir EU-weite Mindeststandards für Lieferketten?",
    title_en: "Do we need EU-wide minimum standards for supply chains?",
    scope: "EU",
  },
  {
    id: "eu-3",
    kind: "Abstimmung",
    topics: ["Soziales", "Arbeit"],
    topics_en: ["Social", "Work"],
    title_de: "Soll die EU Mindeststandards für faire Löhne festlegen?",
    title_en: "Should the EU set minimum standards for fair wages?",
    scope: "EU",
  },
  {
    id: "eu-4",
    kind: "Debattenpunkt",
    topics: ["Energie"],
    topics_en: ["Energy"],
    title_de: "Wie stabilisieren wir Energiepreise in Europa sozial gerecht?",
    title_en: "How do we stabilize energy prices in Europe in a socially fair way?",
    scope: "EU",
  },
  {
    id: "eu-5",
    kind: "Debattenpunkt",
    topics: ["Sicherheit", "Digitales"],
    topics_en: ["Security", "Digital"],
    title_de: "Wie schützen wir kritische Infrastruktur EU-weit vor Cyberangriffen?",
    title_en: "How do we protect critical infrastructure across the EU from cyberattacks?",
    scope: "EU",
  },
  {
    id: "eu-6",
    kind: "Abstimmung",
    topics: ["Transparenz", "Politik"],
    topics_en: ["Transparency", "Politics"],
    title_de: "Soll es EU-weite Regeln für Lobbytransparenz geben?",
    title_en: "Should there be EU-wide rules for lobby transparency?",
    scope: "EU",
  },

  // DE (COUNTRY)
  {
    id: "de-1",
    kind: "Debattenpunkt",
    topics: ["Wohnen"],
    topics_en: ["Housing"],
    title_de: "Wie wird Wohnen bezahlbarer, ohne Neubau zu bremsen?",
    title_en: "How can housing become more affordable without slowing new builds?",
    scope: "COUNTRY",
    country: "DE",
  },
  {
    id: "de-2",
    kind: "Abstimmung",
    topics: ["Mobilität", "Stadt"],
    topics_en: ["Mobility", "City"],
    title_de: "Soll die Stadt mehr Geld für Radwege bereitstellen?",
    title_en: "Should the city allocate more funding for bike lanes?",
    scope: "COUNTRY",
    country: "DE",
  },
  {
    id: "de-3",
    kind: "Abstimmung",
    topics: ["Verkehr"],
    topics_en: ["Transport"],
    title_de: "Soll es ein generelles Tempolimit auf Autobahnen geben?",
    title_en: "Should there be a general speed limit on highways?",
    scope: "COUNTRY",
    country: "DE",
  },
  {
    id: "de-4",
    kind: "Debattenpunkt",
    topics: ["Bildung"],
    topics_en: ["Education"],
    title_de: "Wie wird Bildung gerechter, ohne neue Hürden zu schaffen?",
    title_en: "How can education be fairer without creating new barriers?",
    scope: "COUNTRY",
    country: "DE",
  },
  {
    id: "de-5",
    kind: "Abstimmung",
    topics: ["Finanzen"],
    topics_en: ["Finance"],
    title_de: "Soll die Steuerlast stärker nach Leistungsfähigkeit verteilt werden?",
    title_en: "Should the tax burden be distributed more according to ability to pay?",
    scope: "COUNTRY",
    country: "DE",
  },
  {
    id: "de-6",
    kind: "Debattenpunkt",
    topics: ["Gesundheit", "Pflege"],
    topics_en: ["Health", "Care"],
    title_de: "Wie sichern wir Pflege und Gesundheit langfristig bezahlbar?",
    title_en: "How do we keep care and healthcare affordable long term?",
    scope: "COUNTRY",
    country: "DE",
  },
  {
    id: "de-7",
    kind: "Debattenpunkt",
    topics: ["Digitales", "Verwaltung"],
    topics_en: ["Digital", "Administration"],
    title_de: "Wie wird die Verwaltung digitaler, ohne neue Ausschlüsse?",
    title_en: "How can public administration become more digital without creating new exclusions?",
    scope: "COUNTRY",
    country: "DE",
  },

  // Neighbor examples
  {
    id: "fr-1",
    kind: "Debattenpunkt",
    topics: ["Bildung"],
    topics_en: ["Education"],
    title_de: "Wie sichern wir gleiche Bildungschancen in städtischen und ländlichen Regionen?",
    title_en: "How do we ensure equal education opportunities in urban and rural regions?",
    scope: "COUNTRY",
    country: "FR",
  },
  {
    id: "nl-1",
    kind: "Abstimmung",
    topics: ["Wohnen"],
    topics_en: ["Housing"],
    title_de: "Soll es strengere Regeln gegen Spekulation mit Wohnraum geben?",
    title_en: "Should there be stricter rules against housing speculation?",
    scope: "COUNTRY",
    country: "NL",
  },
  {
    id: "be-1",
    kind: "Debattenpunkt",
    topics: ["Mobilität"],
    topics_en: ["Mobility"],
    title_de: "Wie reduzieren wir Pendlerverkehr, ohne Regionen abzuhängen?",
    title_en: "How do we reduce commuter traffic without leaving regions behind?",
    scope: "COUNTRY",
    country: "BE",
  },
  {
    id: "at-1",
    kind: "Abstimmung",
    topics: ["Energie"],
    topics_en: ["Energy"],
    title_de: "Sollen Energieförderungen stärker sozial gestaffelt werden?",
    title_en: "Should energy subsidies be more strongly tiered by social need?",
    scope: "COUNTRY",
    country: "AT",
  },
  {
    id: "ch-1",
    kind: "Debattenpunkt",
    topics: ["Gesundheit"],
    topics_en: ["Health"],
    title_de: "Wie halten wir Gesundheitskosten stabil, ohne Versorgung zu kürzen?",
    title_en: "How do we keep healthcare costs stable without cutting care?",
    scope: "COUNTRY",
    country: "CH",
  },
  {
    id: "cz-1",
    kind: "Debattenpunkt",
    topics: ["Arbeit"],
    topics_en: ["Work"],
    title_de: "Wie machen wir Arbeitsschutz modern, ohne kleine Betriebe zu überlasten?",
    title_en: "How do we modernize workplace safety without overburdening small businesses?",
    scope: "COUNTRY",
    country: "CZ",
  },
  {
    id: "pl-1",
    kind: "Abstimmung",
    topics: ["Energie"],
    topics_en: ["Energy"],
    title_de: "Soll der Ausbau erneuerbarer Energien beschleunigt werden?",
    title_en: "Should the expansion of renewable energy be accelerated?",
    scope: "COUNTRY",
    country: "PL",
  },

  // Example Region (BW) – adjust as you like
  {
    id: "de-bw-1",
    kind: "Debattenpunkt",
    topics: ["Infrastruktur"],
    topics_en: ["Infrastructure"],
    title_de: "Wie priorisieren wir Sanierung vs. Neubau bei Straßen und Brücken?",
    title_en: "How do we prioritize renovation vs. new builds for roads and bridges?",
    scope: "REGION",
    country: "DE",
    region: "BW",
  },
  {
    id: "de-by-1",
    kind: "Abstimmung",
    topics: ["Bildung"],
    topics_en: ["Education"],
    title_de: "Sollen Schulen mehr Budget für digitale Ausstattung erhalten?",
    title_en: "Should schools receive more budget for digital equipment?",
    scope: "REGION",
    country: "DE",
    region: "BY",
  },
  {
    id: "de-be-1",
    kind: "Debattenpunkt",
    topics: ["Wohnen"],
    topics_en: ["Housing"],
    title_de: "Wie stoppen wir Leerstand, ohne Eigentümer zu überlasten?",
    title_en: "How do we stop vacancy without overburdening owners?",
    scope: "REGION",
    country: "DE",
    region: "BE",
  },
  {
    id: "de-nw-1",
    kind: "Debattenpunkt",
    topics: ["Industrie", "Arbeit"],
    topics_en: ["Industry", "Work"],
    title_de: "Wie sichern wir Industriejobs, ohne Klimaziele zu verfehlen?",
    title_en: "How do we secure industrial jobs without missing climate targets?",
    scope: "REGION",
    country: "DE",
    region: "NW",
  },
];
