/** T0 architecture-only contract: references existing owners, never runtime. */
import type {
  AtomicClaimType,
  PublicationClassification,
} from "../analyze/atomicClaimSourceRelationContract";

export const DECISION_DOSSIER_T0_ROLE = "T0" as const;
export const ARCHITECTURE_CONCEPTS = ["SystemQuestion", "ResearchObject", "ContextEvent", "Metric", "Projection", "Assumption", "PolicyBuildingBlock", "ScenarioSet", "Scenario", "Impact", "Tradeoff", "Comparator", "DecisionBinding"] as const;
export type ArchitectureConcept = (typeof ARCHITECTURE_CONCEPTS)[number];
export type OwnerEntry = Readonly<{ concept: ArchitectureConcept; canonicalOwner: string; canonicalReference: string; t0Responsibility: string; laterTaskOwner: "T1" | "T2" | "T3" | "T4" | "T5" | "T6" | "T7"; allowedReferences: readonly string[]; forbiddenOwnershipDuplication: string; revisionSensitive: boolean; readinessRelevant: boolean }>;
const owner = (value: OwnerEntry) => value;
export const DECISION_DOSSIER_ARCHITECTURE_OWNERS = Object.freeze([
  owner({ concept: "SystemQuestion", canonicalOwner: "CanonicalTopic + DecisionQuestion", canonicalReference: "canonical topic ID + jurisdiction", t0Responsibility: "reference only", laterTaskOwner: "T1", allowedReferences: ["CanonicalTopic", "DecisionQuestion", "JurisdictionContext"], forbiddenOwnershipDuplication: "second topic or decision owner", revisionSensitive: true, readinessRelevant: true }),
  owner({ concept: "ResearchObject", canonicalOwner: "Dossier + ResearchTask", canonicalReference: "dossier ID", t0Responsibility: "reference only", laterTaskOwner: "T2", allowedReferences: ["Dossier", "ResearchTask", "ResearchArtifact"], forbiddenOwnershipDuplication: "second research store", revisionSensitive: true, readinessRelevant: true }),
  owner({ concept: "ContextEvent", canonicalOwner: "Dossier claim/source/revision domain", canonicalReference: "claim/source/revision IDs", t0Responsibility: "reference only", laterTaskOwner: "T3", allowedReferences: ["AtomicClaim", "SourceArtifact", "DossierRevision"], forbiddenOwnershipDuplication: "event truth outside dossier", revisionSensitive: true, readinessRelevant: true }),
  owner({ concept: "Metric", canonicalOwner: "Atomic quantified claim + EvidenceAssessment", canonicalReference: "claim/evidence IDs", t0Responsibility: "require definitional references", laterTaskOwner: "T3", allowedReferences: ["AtomicClaim", "EvidenceAssessment"], forbiddenOwnershipDuplication: "second metric truth", revisionSensitive: true, readinessRelevant: true }),
  owner({ concept: "Projection", canonicalOwner: "Atomic prediction/model provenance", canonicalReference: "claim/model/source IDs", t0Responsibility: "prohibit measurement rendering", laterTaskOwner: "T3", allowedReferences: ["AtomicClaim", "EvidenceAssessment", "DossierRevision"], forbiddenOwnershipDuplication: "second projection owner", revisionSensitive: true, readinessRelevant: true }),
  owner({ concept: "Assumption", canonicalOwner: "Dossier/Atomic evidence context", canonicalReference: "claim/revision IDs", t0Responsibility: "make explicit", laterTaskOwner: "T3", allowedReferences: ["AtomicClaim", "DossierRevision"], forbiddenOwnershipDuplication: "silent default assumption", revisionSensitive: true, readinessRelevant: true }),
  owner({ concept: "PolicyBuildingBlock", canonicalOwner: "Dossier scenario domain", canonicalReference: "future scenario reference", t0Responsibility: "owner boundary only", laterTaskOwner: "T4", allowedReferences: ["Dossier"], forbiddenOwnershipDuplication: "T0 policy runtime", revisionSensitive: true, readinessRelevant: false }),
  owner({ concept: "ScenarioSet", canonicalOwner: "Dossier scenario domain", canonicalReference: "future scenario-set reference", t0Responsibility: "owner boundary only", laterTaskOwner: "T4", allowedReferences: ["Dossier", "DossierRevision"], forbiddenOwnershipDuplication: "T0 scenario store", revisionSensitive: true, readinessRelevant: true }),
  owner({ concept: "Scenario", canonicalOwner: "Dossier scenario domain", canonicalReference: "future scenario reference", t0Responsibility: "owner boundary only", laterTaskOwner: "T4", allowedReferences: ["ScenarioSet", "DossierRevision"], forbiddenOwnershipDuplication: "T0 recommendation", revisionSensitive: true, readinessRelevant: true }),
  owner({ concept: "Impact", canonicalOwner: "Dossier evidence domain", canonicalReference: "claim/evidence/affected-group references", t0Responsibility: "separate observed/modelled/normative", laterTaskOwner: "T5", allowedReferences: ["AtomicClaim", "EvidenceAssessment"], forbiddenOwnershipDuplication: "second impact truth", revisionSensitive: true, readinessRelevant: true }),
  owner({ concept: "Tradeoff", canonicalOwner: "Dossier evidence domain", canonicalReference: "claim/evidence references", t0Responsibility: "separate value judgment", laterTaskOwner: "T5", allowedReferences: ["AtomicClaim", "EvidenceAssessment"], forbiddenOwnershipDuplication: "auto normative conclusion", revisionSensitive: true, readinessRelevant: true }),
  owner({ concept: "Comparator", canonicalOwner: "Dossier evidence domain", canonicalReference: "source/jurisdiction/metric references", t0Responsibility: "require transfer boundary", laterTaskOwner: "T5", allowedReferences: ["SourceArtifact", "JurisdictionContext", "AtomicClaim"], forbiddenOwnershipDuplication: "automatic transfer", revisionSensitive: true, readinessRelevant: true }),
  owner({ concept: "DecisionBinding", canonicalOwner: "Poll/TopicRound", canonicalReference: "poll/topic-round ID + revision refs", t0Responsibility: "staleness invariant only", laterTaskOwner: "T6", allowedReferences: ["Poll", "TopicRound", "DossierRevision", "ScenarioSet", "Scenario"], forbiddenOwnershipDuplication: "dossier activates decision", revisionSensitive: true, readinessRelevant: true }),
] as const);
export function validateArchitectureOwners(entries: readonly OwnerEntry[]): boolean { if (entries.length !== DECISION_DOSSIER_ARCHITECTURE_OWNERS.length) return false; const expected = new Map(DECISION_DOSSIER_ARCHITECTURE_OWNERS.map((value) => [value.concept, value])); const seen = new Set<ArchitectureConcept>(); return entries.every((value) => { const canonical = expected.get(value.concept); if (!canonical || seen.has(value.concept) || !value.canonicalOwner.trim() || !value.canonicalReference.trim() || !value.t0Responsibility.trim() || !value.forbiddenOwnershipDuplication.trim()) return false; seen.add(value.concept); return value.canonicalOwner === canonical.canonicalOwner && value.canonicalReference === canonical.canonicalReference && value.t0Responsibility === canonical.t0Responsibility && value.laterTaskOwner === canonical.laterTaskOwner && value.forbiddenOwnershipDuplication === canonical.forbiddenOwnershipDuplication && value.revisionSensitive === canonical.revisionSensitive && value.readinessRelevant === canonical.readinessRelevant && value.allowedReferences.length === canonical.allowedReferences.length && [...value.allowedReferences].sort().every((reference, index) => reference === [...canonical.allowedReferences].sort()[index]); }); }

export const EPISTEMIC_CATEGORIES = ["FACT", "MEASURED_VALUE", "ESTIMATE", "PROJECTION", "MODEL_RESULT", "ASSUMPTION", "INTERPRETATION", "OPINION", "NORMATIVE_JUDGMENT", "UNKNOWN"] as const;
export type EpistemicCategory = (typeof EPISTEMIC_CATEGORIES)[number];
export const CLAIM_FORM_PRESENTATIONS = ["factual_claim", "measurement", "evidence", "estimate", "projection", "model_result", "assumption", "interpretation", "opinion", "value", "unknown"] as const;
export type ClaimFormPresentation = (typeof CLAIM_FORM_PRESENTATIONS)[number];
export const EPISTEMIC_CLAIM_FORM_COMPATIBILITY_MATRIX: Readonly<Record<EpistemicCategory, readonly ClaimFormPresentation[]>> = Object.freeze({ FACT: ["factual_claim"], MEASURED_VALUE: ["measurement"], ESTIMATE: ["estimate"], PROJECTION: ["projection"], MODEL_RESULT: ["model_result"], ASSUMPTION: ["assumption"], INTERPRETATION: ["interpretation"], OPINION: ["opinion"], NORMATIVE_JUDGMENT: ["value"], UNKNOWN: ["unknown"] });
/** Claim-form compatibility, including measurement, is never verified presentation. */
export function canRenderClaimForm(category: EpistemicCategory, renderedAs: ClaimFormPresentation): boolean { return EPISTEMIC_CLAIM_FORM_COMPATIBILITY_MATRIX[category].includes(renderedAs); }
export type CanonicalEvidenceResolution = Readonly<{ canonicalOwner: "AtomicClaim/EvidenceAssessment"; publicationClassification: PublicationClassification; evidenceReference: string; relationStatus: "resolved" | "unresolved" | "invalid"; assessmentStatus: "supported" | "contested" | "contradicted" | "insufficient" | "unknown"; reviewStatus: "verified" | "pending" | "rejected" | "unknown"; freshnessStatus: "verified_fresh" | "stale" | "unknown"; conflictStatus: "none" | "open" | "unresolved" | "resolved"; revision: string | null; resolutionReceiptReference: string | null }>;
export function hasCanonicalVerifiedEvidence(value: CanonicalEvidenceResolution | null | undefined): boolean { return Boolean(value && value.canonicalOwner === "AtomicClaim/EvidenceAssessment" && value.publicationClassification === "publishable_as_externally_verified_fact" && present(value.evidenceReference) && value.relationStatus === "resolved" && value.assessmentStatus === "supported" && value.reviewStatus === "verified" && value.freshnessStatus === "verified_fresh" && (value.conflictStatus === "none" || value.conflictStatus === "resolved") && present(value.revision ?? undefined) && present(value.resolutionReceiptReference ?? undefined)); }
export function canPresentAsVerifiedFact(category: EpistemicCategory, resolution: CanonicalEvidenceResolution | null | undefined): boolean { return category === "FACT" && hasCanonicalVerifiedEvidence(resolution); }
export function canPresentAsVerifiedMeasurement(category: EpistemicCategory, resolution: CanonicalEvidenceResolution | null | undefined): boolean { return category === "MEASURED_VALUE" && hasCanonicalVerifiedEvidence(resolution); }
export type StructuredProvenance = Readonly<{ sourceReference?: string; evidenceReference?: string; metricDefinitionReference?: string; period?: string; populationScope?: string; unit?: string; denominator?: string; method?: string; uncertainty?: string; modelReference?: string; basisPeriod?: string; assumptions?: readonly string[]; revision?: string; modelVersion?: string }>;
const present = (value: string | undefined) => Boolean(value?.trim());
export function hasRequiredProvenance(category: EpistemicCategory, value: StructuredProvenance): boolean { switch (category) { case "FACT": return present(value.sourceReference) && present(value.evidenceReference) && present(value.populationScope); case "MEASURED_VALUE": return present(value.sourceReference) && present(value.evidenceReference) && present(value.metricDefinitionReference) && present(value.period) && present(value.populationScope) && present(value.unit) && present(value.denominator); case "ESTIMATE": return present(value.method) && present(value.sourceReference) && present(value.uncertainty); case "PROJECTION": return present(value.modelReference) && present(value.basisPeriod) && Boolean(value.assumptions?.length) && present(value.revision); case "MODEL_RESULT": return present(value.modelReference) && present(value.modelVersion ?? value.revision); case "ASSUMPTION": return present(value.sourceReference) && present(value.revision); case "INTERPRETATION": return present(value.sourceReference) && present(value.evidenceReference) && present(value.populationScope); case "OPINION": case "NORMATIVE_JUDGMENT": case "UNKNOWN": return false; } }

export const REQUIRED_DECISION_DIMENSIONS = ["system_question", "research", "context", "metric", "projection", "assumption", "scenario", "impact", "tradeoff", "comparator", "decision_binding"] as const;
export type RequiredDecisionDimension = (typeof REQUIRED_DECISION_DIMENSIONS)[number];
export type CanonicalMaterialityReviewResolution = Readonly<{ canonicalOwner: "Dossier/Atomic evidence context"; reviewStatus: "verified" | "pending" | "rejected" | "unknown"; basisStatus: "verified" | "unresolved" | "unknown"; revision: string | null; receiptReference: string | null }>;
export type MaterialityDecision = Readonly<{ classification: "material" | "non_material"; rationale: string; basisReference: string | null; reviewStatus: "reviewed" | "pending" | "rejected"; reviewedBy: string | null; revision: string | null; canonicalReviewResolution?: CanonicalMaterialityReviewResolution | null }>;
export type MaterialDimension = Readonly<{ key: RequiredDecisionDimension; materiality: MaterialityDecision; status: "complete" | "gap" | "unknown"; evidenceReferences: readonly string[]; evidenceResolution?: CanonicalEvidenceResolution | null; reviewStatus: "reviewed" | "pending" | "rejected"; gap: string | null; freshness: "fresh" | "stale" | "unknown"; revision: string | null }>;
const reviewedMateriality = (value: MaterialityDecision) => value.reviewStatus === "reviewed" && present(value.rationale) && present(value.reviewedBy ?? undefined) && present(value.revision ?? undefined) && (value.classification === "material" || Boolean(present(value.basisReference ?? undefined) && value.canonicalReviewResolution && value.canonicalReviewResolution.canonicalOwner === "Dossier/Atomic evidence context" && value.canonicalReviewResolution.reviewStatus === "verified" && value.canonicalReviewResolution.basisStatus === "verified" && present(value.canonicalReviewResolution.revision ?? undefined) && present(value.canonicalReviewResolution.receiptReference ?? undefined)));
const hasCompleteRequiredSet = (values: readonly MaterialDimension[]) => { const keys = new Set(values.map((value) => value.key)); return values.length === REQUIRED_DECISION_DIMENSIONS.length && keys.size === REQUIRED_DECISION_DIMENSIONS.length && REQUIRED_DECISION_DIMENSIONS.every((key) => keys.has(key)); };
const hardBlocked = (value: MaterialDimension) => !reviewedMateriality(value.materiality) || (value.materiality.classification === "material" && (value.status !== "complete" || value.reviewStatus !== "reviewed" || !hasCanonicalVerifiedEvidence(value.evidenceResolution) || value.freshness !== "fresh" || !present(value.revision ?? undefined) || value.gap !== null));
export function readyForHumanDeliberation(values: readonly MaterialDimension[]): boolean { return hasCompleteRequiredSet(values) && values.every((value) => reviewedMateriality(value.materiality) && value.reviewStatus !== "rejected"); }
export function decisionReady(values: readonly MaterialDimension[]): boolean { return hasCompleteRequiredSet(values) && values.every((value) => !hardBlocked(value)); }

export type DecisionBindingSnapshot = Readonly<{ boundRevision: string; materialRevisions: Readonly<Record<string, string>> }>;
const hasMalformedMaterialRevisions = (value: Readonly<Record<string, string>>) => Object.entries(value).some(([key, revision]) => !present(key) || !present(revision));
export function isBindingStale(binding: DecisionBindingSnapshot, current: DecisionBindingSnapshot): boolean { if (!present(binding.boundRevision) || !present(current.boundRevision) || binding.boundRevision !== current.boundRevision || hasMalformedMaterialRevisions(binding.materialRevisions) || hasMalformedMaterialRevisions(current.materialRevisions)) return true; const keys = new Set([...Object.keys(binding.materialRevisions), ...Object.keys(current.materialRevisions)]); return [...keys].some((key) => binding.materialRevisions[key] !== current.materialRevisions[key]); }
export type MetricDefinition = Readonly<{ metricKey: string; numerator: string; denominator: string; population: string; jurisdictionScope: string; timeBasis: string; unit: string; methodology: string }>;
export type MetricCompatibility = "compatible" | "incompatible" | "requires_harmonization" | "unknown";
const normalized = (value: string) => value.trim().replace(/\s+/g, " ").toLowerCase();
export function compareMetricDefinitions(left: MetricDefinition, right: MetricDefinition): MetricCompatibility { if (Object.values(left).some((value) => !value.trim()) || Object.values(right).some((value) => !value.trim())) return "unknown"; if (normalized(left.metricKey) !== normalized(right.metricKey)) return "incompatible"; const keys: Array<keyof MetricDefinition> = ["numerator", "denominator", "population", "jurisdictionScope", "timeBasis", "unit", "methodology"]; return keys.every((key) => normalized(left[key]) === normalized(right[key])) ? "compatible" : "requires_harmonization"; }
export type ComparatorInput = Readonly<{ jurisdiction: string; targetJurisdiction: string; institutions: readonly string[]; contributionDefinition: string; benefitDefinition: string; originalLanguage: string; readingLanguage: string }>;
export function evaluateComparator(value: ComparatorInput) { const referenceable = Boolean(value.jurisdiction && value.institutions.length && value.contributionDefinition && value.benefitDefinition && value.originalLanguage && value.readingLanguage); return { referenceable, transferability: referenceable ? "requires_review" as const : "not_assessed" as const }; }
export type SourceLineage = Readonly<{ id: string; parentId: string | null }>;
export type SourceIndependenceResolution = Readonly<{ sourceFamilyId: string; independence: "verified_independent_root" | "known_derived" | "independence_unknown"; resolutionReceiptReference: string | null }>;
export type VerifiedEvidenceFamilyResult = { status: "ok"; independentFamilies: number } | { status: "unknown_independence" } | { status: "invalid"; reason: "empty_id" | "duplicate_id" | "missing_parent" | "self_parent" | "cycle" };
export type StructuralLineageRootResult = { status: "ok"; structuralRoots: number } | { status: "invalid"; reason: "empty_id" | "duplicate_id" | "missing_parent" | "self_parent" | "cycle" };
/** Structural roots are never a verified independent-evidence count. */
export function countStructuralLineageRoots(values: readonly SourceLineage[]): StructuralLineageRootResult { const parents = new Map<string, string | null>(); for (const value of values) { if (!value.id) return { status: "invalid", reason: "empty_id" }; if (parents.has(value.id)) return { status: "invalid", reason: "duplicate_id" }; if (value.parentId === value.id) return { status: "invalid", reason: "self_parent" }; parents.set(value.id, value.parentId); } for (const parent of parents.values()) if (parent && !parents.has(parent)) return { status: "invalid", reason: "missing_parent" }; const roots = new Set<string>(); for (const id of parents.keys()) { const seen = new Set<string>(); let current = id; while (parents.get(current)) { if (seen.has(current)) return { status: "invalid", reason: "cycle" }; seen.add(current); current = parents.get(current)!; } roots.add(current); } return { status: "ok", structuralRoots: roots.size }; }
export function countVerifiedIndependentEvidenceFamilies(lineage: readonly SourceLineage[], resolutions: readonly SourceIndependenceResolution[]): VerifiedEvidenceFamilyResult { const structural = countStructuralLineageRoots(lineage); if (structural.status === "invalid") return structural; const roots = new Set<string>(); const parents = new Map(lineage.map((item) => [item.id, item.parentId])); for (const id of parents.keys()) { let current = id; while (parents.get(current)) current = parents.get(current)!; roots.add(current); } const resolution = new Map(resolutions.map((value) => [value.sourceFamilyId, value])); for (const root of roots) { const value = resolution.get(root); if (!value || value.independence !== "verified_independent_root" || !present(value.resolutionReceiptReference ?? undefined)) return { status: "unknown_independence" }; } return { status: "ok", independentFamilies: roots.size }; }
export function t0Allows(action: string): boolean { return (["reference_owner", "validate_fixture", "validate_architecture"] as readonly string[]).includes(action); }
export function t0CanReleasePublicCandidate(): false { return false; }
/** Total mapping from the canonical AtomicClaim vocabulary; null is controlled T0 abstention. */
export const CANONICAL_ATOMIC_CLAIM_TYPE_TO_T0_CATEGORY: Readonly<Record<AtomicClaimType, EpistemicCategory | null>> = Object.freeze({ reported_speech: null, personal_experience: null, factual_claim: "FACT", quantified_claim: "FACT", causal_claim: null, system_hypothesis: null, mechanism_hypothesis: null, interpretation: "INTERPRETATION", normative_position: "NORMATIVE_JUDGMENT", prediction: "PROJECTION", non_checkable_opinion: "OPINION" });
/** T0 architecture projections only; these are not persisted AtomicClaim types. */
export const T0_DERIVED_EPISTEMIC_CATEGORIES = ["MEASURED_VALUE", "ESTIMATE", "MODEL_RESULT", "ASSUMPTION", "UNKNOWN"] as const;
export function mapCanonicalAtomicClaimType(value: AtomicClaimType): EpistemicCategory | null { return CANONICAL_ATOMIC_CLAIM_TYPE_TO_T0_CATEGORY[value]; }
