import { describe, expect, it } from "vitest";
import { DECISION_DOSSIER_ARCHITECTURE_OWNERS, canRender, decisionReady, hasRequiredProvenance, isBindingStale, readyForHumanDeliberation, t0Allows, t0CanReleasePublicCandidate, validateArchitectureOwners } from "@/features/dossier/decisionDossierArchitectureContract";

const complete = { material: true, status: "complete" as const, evidenceReferences: ["e1"], reviewStatus: "reviewed" as const, gap: null, freshness: "fresh" as const, revision: "r1" };

describe("decision dossier T0 architecture contract", () => {
  it("maps every owner exactly once and fails closed for missing or duplicate owners", () => { expect(validateArchitectureOwners(DECISION_DOSSIER_ARCHITECTURE_OWNERS)).toBe(true); expect(validateArchitectureOwners(DECISION_DOSSIER_ARCHITECTURE_OWNERS.slice(1))).toBe(false); expect(validateArchitectureOwners([...DECISION_DOSSIER_ARCHITECTURE_OWNERS, DECISION_DOSSIER_ARCHITECTURE_OWNERS[0]])).toBe(false); });
  it("keeps the Swedish pension comparator referenceable but non-transferable", () => { const comparator = DECISION_DOSSIER_ARCHITECTURE_OWNERS.find((owner) => owner.concept === "Comparator")!; expect(comparator.allowedReferences).toContain("JurisdictionContext"); expect(comparator.forbiddenOwnershipDuplication).toContain("automatic transfer"); });
  it("keeps UNKNOWN material in a low-data jurisdiction and blocks decision readiness", () => { const lowData = { ...complete, status: "unknown" as const, evidenceReferences: [], gap: "robust baseline missing", freshness: "unknown" as const }; expect(readyForHumanDeliberation([lowData])).toBe(true); expect(decisionReady([lowData])).toBe(false); });
  it("does not render a projection as measurement and requires model provenance", () => { expect(canRender("PROJECTION", "measurement")).toBe(false); expect(hasRequiredProvenance("PROJECTION", [])).toBe(false); });
  it("does not treat a fact/value pair as one claim", () => { expect(canRender("FACT", "fact")).toBe(true); expect(canRender("NORMATIVE_JUDGMENT", "fact")).toBe(false); });
  it("requires measurement definitions before factual contradiction or equivalence", () => { const metric = DECISION_DOSSIER_ARCHITECTURE_OWNERS.find((owner) => owner.concept === "Metric")!; expect(metric.t0Responsibility).toContain("definitional"); expect(metric.allowedReferences).toContain("EvidenceAssessment"); });
  it("preserves source-family lineage rather than inventing independent evidence", () => { const research = DECISION_DOSSIER_ARCHITECTURE_OWNERS.find((owner) => owner.concept === "ResearchObject")!; expect(research.allowedReferences).toContain("ResearchArtifact"); expect(canRender("OPINION", "evidence")).toBe(false); });
  it("invalidates a binding after a material projection or scenario revision", () => { expect(isBindingStale({ boundRevision: "d1", materialRevisions: { projection: "p1", scenario: "s1" } }, { projection: "p2", scenario: "s1" })).toBe(true); });
  it("does not allow T0 to create scenarios, research success, decisions, or public candidates", () => { expect(t0Allows("generate_scenario")).toBe(false); expect(t0Allows("research_success")).toBe(false); expect(t0Allows("activate_decision")).toBe(false); expect(t0CanReleasePublicCandidate()).toBe(false); });
  it("has no runtime action or public guard bypass surface", () => { expect(t0Allows("database_access")).toBe(false); expect(t0Allows("provider_call")).toBe(false); expect(t0Allows("publish")).toBe(false); expect(t0Allows("modify_user_state")).toBe(false); expect(t0CanReleasePublicCandidate()).toBe(false); });
});
