import {
  MarketingCampaignControlProfilesSchema,
  MarketingMetricSnapshotsSchema,
  type MarketingCampaignControlProfile,
  type MarketingMetricSnapshot,
} from "./contracts";

const NO_WINDOW = { startsAt: null, endsAt: null } as const;

const CAMPAIGN_PROFILES: MarketingCampaignControlProfile[] = [
  {
    campaignId: "CAM-EDB-01",
    primarySegment: "b2c",
    segments: ["b2c", "b2b", "b2g"],
    audienceLabels: ["Bürger", "Redaktionen", "Initiativen", "Kommunen"],
    regionKeys: ["germany", "dach", "international"],
    reachScopes: ["national", "international"],
    locales: ["de-DE", "en-GB"],
    promotion: "mixed",
    plannedChannels: ["edebatte", "website", "instagram", "linkedin", "facebook", "youtube_shorts", "meta_ads", "linkedin_ads"],
    objective: "eDebatte verständlich erklären und qualifizierte Produktnutzung auslösen.",
    primaryKpi: "product_actions_completed",
    secondaryKpis: ["qualified_inquiries", "link_clicks", "reach", "downloads"],
    reportingWindow: NO_WINDOW,
  },
  {
    campaignId: "CAM-CONTENT-02",
    primarySegment: "b2c",
    segments: ["b2c", "b2b"],
    audienceLabels: ["Öffentlichkeit", "Community", "Redaktionen"],
    regionKeys: ["germany", "international"],
    reachScopes: ["national", "international"],
    locales: ["de-DE", "en-GB"],
    promotion: "mixed",
    plannedChannels: ["edebatte", "instagram", "linkedin", "facebook", "newsletter", "meta_ads"],
    objective: "Den Debattenstand als wiederkehrendes, nachvollziehbares Informationsformat etablieren.",
    primaryKpi: "product_actions_started",
    secondaryKpis: ["saves", "shares", "link_clicks", "reach"],
    reportingWindow: NO_WINDOW,
  },
  {
    campaignId: "CAM-VOXY-03",
    primarySegment: "b2c",
    segments: ["b2c", "b2b"],
    audienceLabels: ["Social-Media-Nutzer", "Community", "Redaktionen"],
    regionKeys: ["germany", "international"],
    reachScopes: ["national", "international"],
    locales: ["de-DE", "en-GB"],
    promotion: "mixed",
    plannedChannels: ["tiktok", "instagram_reels", "youtube_shorts", "edebatte", "meta_ads"],
    objective: "Voxy als verständlichen Guide für Produktlogik und Debattenstände etablieren.",
    primaryKpi: "completion_rate",
    secondaryKpis: ["saves", "shares", "link_clicks", "product_actions_started"],
    reportingWindow: NO_WINDOW,
  },
  {
    campaignId: "CAM-SOURCE-04",
    primarySegment: "b2c",
    segments: ["b2c", "b2b"],
    audienceLabels: ["Bürger", "Medien", "Wissenschaft"],
    regionKeys: ["germany", "international"],
    reachScopes: ["national", "international"],
    locales: ["de-DE", "en-GB"],
    promotion: "organic",
    plannedChannels: ["edebatte", "website", "linkedin", "newsletter", "press"],
    objective: "Quellenlage, Gegenpositionen und offene Fragen als Produktnutzen zeigen.",
    primaryKpi: "product_actions_started",
    secondaryKpis: ["link_clicks", "downloads", "qualified_inquiries"],
    reportingWindow: NO_WINDOW,
  },
  {
    campaignId: "CAM-LANG-05",
    primarySegment: "b2c",
    segments: ["b2c", "b2b", "b2g"],
    audienceLabels: ["Mehrsprachige Communities", "Redaktionen", "Kommunen"],
    regionKeys: ["germany", "europe", "international"],
    reachScopes: ["regional", "national", "international"],
    locales: ["de-DE", "en-GB", "tr-TR", "ar"],
    promotion: "organic",
    plannedChannels: ["edebatte", "website", "instagram", "linkedin", "youtube"],
    objective: "Die Sprachbrücke mit Originalerhalt für nationale und internationale Zielgruppen belegen.",
    primaryKpi: "product_actions_completed",
    secondaryKpis: ["qualified_inquiries", "shares", "downloads"],
    reportingWindow: NO_WINDOW,
  },
  {
    campaignId: "CAM-MEDIA-06",
    primarySegment: "b2b",
    segments: ["b2b"],
    audienceLabels: ["Redaktionen", "Verlage", "Podcasts", "Fachmedien"],
    regionKeys: ["germany", "dach", "international"],
    reachScopes: ["national", "international"],
    locales: ["de-DE", "en-GB"],
    promotion: "mixed",
    plannedChannels: ["linkedin", "email", "press", "download", "linkedin_ads"],
    objective: "Qualifizierte Gespräche mit Medienpartnern und Redaktionen auslösen.",
    primaryKpi: "qualified_inquiries",
    secondaryKpis: ["email_replies", "downloads", "link_clicks"],
    reportingWindow: NO_WINDOW,
  },
  {
    campaignId: "CAM-SCIENCE-07",
    primarySegment: "b2b",
    segments: ["b2b", "b2g"],
    audienceLabels: ["Hochschulen", "Institute", "Forschungsnetzwerke"],
    regionKeys: ["germany", "europe", "international"],
    reachScopes: ["national", "international"],
    locales: ["de-DE", "en-GB"],
    promotion: "organic",
    plannedChannels: ["linkedin", "email", "newsletter", "download", "press"],
    objective: "Wissenschaftliche Kooperationen und belastbare Evidenzpartnerschaften anbahnen.",
    primaryKpi: "qualified_inquiries",
    secondaryKpis: ["email_replies", "downloads", "link_clicks"],
    reportingWindow: NO_WINDOW,
  },
  {
    campaignId: "CAM-TECH-08",
    primarySegment: "b2b",
    segments: ["b2b", "b2g"],
    audienceLabels: ["Technologiepartner", "Open-Source-Projekte", "Infrastrukturpartner"],
    regionKeys: ["germany", "europe", "international"],
    reachScopes: ["national", "international"],
    locales: ["de-DE", "en-GB"],
    promotion: "organic",
    plannedChannels: ["linkedin", "email", "download", "press", "website"],
    objective: "Technische Kooperationen ohne inhaltliche Sonderrechte qualifizieren.",
    primaryKpi: "qualified_inquiries",
    secondaryKpis: ["email_replies", "downloads", "link_clicks"],
    reportingWindow: NO_WINDOW,
  },
  {
    campaignId: "CAM-MUNI-09",
    primarySegment: "b2g",
    segments: ["b2g", "b2b"],
    audienceLabels: ["Kommunen", "Verwaltungen", "öffentliche Einrichtungen"],
    regionKeys: ["germany-local", "germany-regional", "germany"],
    reachScopes: ["local", "regional", "national"],
    locales: ["de-DE", "en-GB"],
    promotion: "mixed",
    plannedChannels: ["email", "linkedin", "download", "website", "linkedin_ads"],
    objective: "Qualifizierte B2G-Anwendungsfälle und Gespräche für nachvollziehbare Beteiligung erzeugen.",
    primaryKpi: "qualified_inquiries",
    secondaryKpis: ["email_replies", "downloads", "landing_page_views"],
    reportingWindow: NO_WINDOW,
  },
  {
    campaignId: "CAM-COMMUNITY-10",
    primarySegment: "b2c",
    segments: ["b2c", "b2b"],
    audienceLabels: ["Initiativen", "Vereine", "NGOs", "lokale Gruppen"],
    regionKeys: ["germany-local", "germany-regional", "germany"],
    reachScopes: ["local", "regional", "national"],
    locales: ["de-DE", "en-GB"],
    promotion: "organic",
    plannedChannels: ["instagram", "facebook", "linkedin", "email", "edebatte"],
    objective: "Initiativen und Communitys zu einer strukturierten Anliegenvorbereitung führen.",
    primaryKpi: "product_actions_completed",
    secondaryKpis: ["shares", "saves", "qualified_inquiries"],
    reportingWindow: NO_WINDOW,
  },
  {
    campaignId: "CAM-VOG-11",
    primarySegment: "b2c",
    segments: ["b2c"],
    audienceLabels: ["persönliche Mitglieder", "Missionsunterstützer"],
    regionKeys: ["germany", "international"],
    reachScopes: ["national", "international"],
    locales: ["de-DE", "en-GB"],
    promotion: "mixed",
    plannedChannels: ["website", "email", "newsletter", "instagram", "linkedin", "meta_ads"],
    objective: "Interesse an persönlicher VoiceOpenGov-Mitgliedschaft qualifizieren.",
    primaryKpi: "qualified_inquiries",
    secondaryKpis: ["email_replies", "link_clicks", "downloads"],
    reportingWindow: NO_WINDOW,
  },
  {
    campaignId: "CAM-VOG-PARTNER-12",
    primarySegment: "b2b",
    segments: ["b2b", "b2g"],
    audienceLabels: ["Organisationen", "Partner", "Kommunen", "Förderer"],
    regionKeys: ["germany", "europe", "international"],
    reachScopes: ["national", "international"],
    locales: ["de-DE", "en-GB"],
    promotion: "mixed",
    plannedChannels: ["linkedin", "email", "download", "press", "linkedin_ads"],
    objective: "Qualifizierte Partnergespräche innerhalb der bestätigten Einflussgrenzen erzeugen.",
    primaryKpi: "qualified_inquiries",
    secondaryKpis: ["email_replies", "downloads", "link_clicks"],
    reportingWindow: NO_WINDOW,
  },
  {
    campaignId: "CAM-WHITE-LABEL-13",
    primarySegment: "b2b",
    segments: ["b2b", "b2g"],
    audienceLabels: ["Kommunen", "Verbände", "Organisationen"],
    regionKeys: ["germany", "dach", "international"],
    reachScopes: ["national", "international"],
    locales: ["de-DE", "en-GB"],
    promotion: "organic",
    plannedChannels: ["linkedin", "email", "download", "website"],
    objective: "White-Label- und Co-Branding-Anwendungsfälle qualifizieren, ohne sie vorzeitig öffentlich zu bewerben.",
    primaryKpi: "qualified_inquiries",
    secondaryKpis: ["email_replies", "downloads", "landing_page_views"],
    reportingWindow: NO_WINDOW,
  },
  {
    campaignId: "CAM-V4G-14",
    primarySegment: "b2c",
    segments: ["b2c", "b2b", "b2g"],
    audienceLabels: ["Bürger", "Civic-Tech", "Forschung", "öffentliche Akteure"],
    regionKeys: ["germany", "europe", "international"],
    reachScopes: ["national", "international"],
    locales: ["de-DE", "en-GB"],
    promotion: "organic",
    plannedChannels: ["website", "linkedin", "instagram", "youtube_shorts", "newsletter"],
    objective: "Vote4Gov als Denkwerkstatt für nachvollziehbare Governance-Vergleiche und transparent gekennzeichnete Alternativhypothesen etablieren.",
    primaryKpi: "product_actions_started",
    secondaryKpis: ["saves", "shares", "link_clicks", "qualified_inquiries"],
    reportingWindow: NO_WINDOW,
  },
];

const METRIC_SNAPSHOTS: MarketingMetricSnapshot[] = [];

export function getMarketingCampaignControlProfiles(): MarketingCampaignControlProfile[] {
  return MarketingCampaignControlProfilesSchema.parse(CAMPAIGN_PROFILES);
}

export function getMarketingMetricSnapshots(): MarketingMetricSnapshot[] {
  return MarketingMetricSnapshotsSchema.parse(METRIC_SNAPSHOTS);
}
