import {
  VOXY_PRODUCT_PROMO_SCHEMA_VERSION,
  type VoxyProductPromoProduction,
} from "./productPromoProduction";

export const VOXY_PRODUCT_PROMO_PRODUCTIONS = {
  "edebatte-democracy-update-01": {
    schemaVersion: VOXY_PRODUCT_PROMO_SCHEMA_VERSION,
    productionId: "edebatte-democracy-update-01",
    title: "eDebatte · Demokratie kann mehr",
    brand: "edebatte",
    format: "vertical_9_16",
    motionProfile: "social",
    voice: "D1",
    visualGrammar: "PRODUCT_SURFACE → INTERACTION → VALUE → SYNTHESIS → CTA",
    assetRootPolicy: {
      environmentVariable: "VOXY_PRODUCTION_ASSET_ROOT",
      productionSubdirectory: "edebatte-democracy-update-01",
      assetsSubdirectory: "assets",
      rawAssetsNeverCommitted: true,
      sha256ManifestRequired: true,
    },
    sources: [
      {
        id: "edebatte-home",
        publisher: "eDebatte",
        title: "eDebatte öffentliche Startseite",
        url: "https://www.edebatte.org/",
        route: "/",
        sourceClass: "first_party_product_surface",
      },
      {
        id: "edebatte-product-principle",
        publisher: "eDebatte",
        title: "Eine Frage. Viele Perspektiven. Ein klareres Bild.",
        sourceClass: "editorial_principle",
      },
    ],
    claims: [
      {
        id: "democracy-can-be-more-than-election-day",
        classification: "editorial_principle",
        text: "Demokratische Beteiligung kann auch zwischen Wahlen stattfinden.",
        product: "shared",
        sourceIds: ["edebatte-product-principle"],
        marketable: true,
      },
      {
        id: "edebatte-public-participation",
        classification: "current_capability",
        text: "eDebatte bietet öffentliche Beteiligungs- und Frageoberflächen.",
        product: "edebatte",
        sourceIds: ["edebatte-home"],
        marketable: true,
      },
      {
        id: "continuous-binding-mandate",
        classification: "future_intent",
        text: "Ein allgemeines dauerhaft bindendes digitales Mandat wird nicht als vorhandene Funktion beworben.",
        product: "edebatte",
        sourceIds: [],
        marketable: false,
      },
    ],
    assets: [
      {
        id: "product-home",
        role: "product_surface",
        product: "edebatte",
        acquisition: { kind: "private_local_file", relativePath: "01-product-home.png" },
        alt: "eDebatte Startseite mit der Aussage Eine Frage. Viele Perspektiven. Ein klareres Bild.",
        required: true,
        purpose: "Produktidentität und Einstieg zeigen",
      },
      {
        id: "product-participation-entry",
        role: "product_surface",
        product: "edebatte",
        acquisition: { kind: "private_local_file", relativePath: "02-participation-entry.png" },
        alt: "eDebatte Oberfläche mit Mitmachen und Kostenlos starten",
        required: true,
        purpose: "niedrigschwelligen Einstieg in die Beteiligung zeigen",
      },
      {
        id: "product-demo-ballot",
        role: "product_surface",
        product: "edebatte",
        acquisition: { kind: "private_local_file", relativePath: "03-demo-ballot.png" },
        alt: "eDebatte Demo-Frage mit vier Antwortoptionen",
        required: true,
        purpose: "konkrete Interaktion statt abstrakter Produktbehauptung zeigen",
      },
    ],
    beats: [
      {
        id: "hook",
        stage: "HOOK",
        narration: "Wir nennen es Wahljahr. Aber welche Wahl haben wir eigentlich? Ein Kreuz. Und die Tage dazwischen?",
        onScreenText: ["WAHLJAHR.", "ABER WELCHE WAHL HABEN WIR EIGENTLICH?"],
        minimumReadableSeconds: 1.5,
      },
      {
        id: "product-entry",
        stage: "PRODUCT_SURFACE",
        narration: "Demokratie kann mehr. Sie kann dort anfangen, wo eine Frage entsteht.",
        onScreenText: ["DEMOKRATIE KANN MEHR."],
        assetIds: ["product-home"],
        claimIds: ["democracy-can-be-more-than-election-day"],
        minimumReadableSeconds: 2,
      },
      {
        id: "participation",
        stage: "INTERACTION",
        narration: "Nicht nur kommentieren. Mitmachen, eine Perspektive ergänzen oder selbst eine Frage starten.",
        onScreenText: ["NICHT NUR KOMMENTIEREN.", "MITMACHEN."],
        assetIds: ["product-participation-entry"],
        claimIds: ["edebatte-public-participation"],
        minimumReadableSeconds: 2,
      },
      {
        id: "demo",
        stage: "VALUE",
        narration: "Eine Frage. Mehr als eine Perspektive. Und ein Bild, das klarer wird, statt nur lauter.",
        onScreenText: ["EINE FRAGE.", "VIELE PERSPEKTIVEN.", "EIN KLARERES BILD."],
        assetIds: ["product-demo-ballot"],
        minimumReadableSeconds: 2,
      },
      {
        id: "synthesis",
        stage: "SYNTHESIS",
        narration: "Vielleicht braucht Demokratie keine neue Lautstärke. Vielleicht braucht sie bessere Beteiligung.",
        onScreenText: ["BETEILIGUNG STATT NUR LAUTSTÄRKE."],
        minimumReadableSeconds: 2,
      },
      {
        id: "cta",
        stage: "CTA",
        narration: "eDebatte. Probier es aus.",
        onScreenText: ["EDEBATTE.ORG", "JETZT AUSPROBIEREN"],
        minimumReadableSeconds: 2,
      },
    ],
    output: {
      basename: "edebatte-democracy-update-01",
      captions: true,
      manifest: true,
      sourceManifest: true,
      assetManifest: true,
    },
    productionEligible: false,
    autoPublish: false,
  },
} as const satisfies Record<string, VoxyProductPromoProduction>;

export type VoxyProductPromoProductionId = keyof typeof VOXY_PRODUCT_PROMO_PRODUCTIONS;
