"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { getGoToMarketTemplate } from "@features/pricing/goToMarketPackaging";
import { createEmptyManualAnlassraumSetup, sanitizeManualAnlassraumSetup, type ManualAnlassraumAiSupportMode, type ManualAnlassraumCommunityOptionsMode, type ManualAnlassraumSetup } from "@/features/surfaces/runden/manualAnlassraumSetup";

const STORAGE_KEY = "manual-anlassraum-setup.v1";
type Props = { initialTemplateId?: string | null };
type AnswerMode = "fixed" | "suggestions";
type VoxyMode = "shared_intelligence" | "manual_only" | null;
function saveSetup(setup: ManualAnlassraumSetup) { window.localStorage.setItem(STORAGE_KEY, JSON.stringify(sanitizeManualAnlassraumSetup(setup))); }

export default function GuidedBallotStart({ initialTemplateId = null }: Props) {
  const template = useMemo(() => getGoToMarketTemplate(initialTemplateId), [initialTemplateId]);
  const [step, setStep] = useState(1);
  const [question, setQuestion] = useState(template?.question.de ?? "");
  const [options, setOptions] = useState<string[]>(template ? [...template.options.de] : ["", "", ""]);
  const [answerMode, setAnswerMode] = useState<AnswerMode>("suggestions");
  const [voxyMode, setVoxyMode] = useState<VoxyMode>(null);
  useEffect(() => { if (template) { setQuestion(template.question.de); setOptions([...template.options.de]); } }, [template]);
  const visibleOptions = options.filter((option) => option.trim());
  const canContinueQuestion = question.trim().length >= 8;
  const canFinish = canContinueQuestion && visibleOptions.length >= 2;
  function updateOption(index: number, value: string) { setOptions((current) => current.map((option, i) => i === index ? value : option)); }
  function persistCurrentSetup() {
    const communityOptionsMode: ManualAnlassraumCommunityOptionsMode = answerMode === "suggestions" ? "review_required" : "disabled";
    const aiSupportMode: ManualAnlassraumAiSupportMode = voxyMode === "shared_intelligence" ? "optional_suggestions" : "disabled";
    saveSetup(sanitizeManualAnlassraumSetup({ ...createEmptyManualAnlassraumSetup(), title: question.trim().replace(/[?.!]$/, "").slice(0, 120), votingQuestion: question, description: "", options, communityOptionsMode, aiSupportMode, visibility: "private_draft", scope: "public", nextStep: "save_draft" }));
  }
  function finishVoxyChoice() { if (!voxyMode) return; persistCurrentSetup(); setStep(5); }
  function openDetails() { persistCurrentSetup(); const nextUrl = new URL(window.location.href); nextUrl.searchParams.set("details", "1"); window.location.assign(nextUrl.toString()); }
  const loginNext = "/runden/new?gtm=1&details=1&source=guided-share";
  const primary = "inline-flex min-h-13 items-center rounded-full bg-cyan-500 px-7 py-3 font-black text-slate-950 disabled:opacity-30";
  const back = "text-sm font-bold text-[rgb(var(--muted))] hover:text-[rgb(var(--fg))]";

  return <section className="mx-auto w-full max-w-3xl">
    <div className="mb-8 flex items-center justify-between gap-4"><p className="text-xs font-black uppercase tracking-[0.18em] text-cyan-700 dark:text-cyan-300">Eine Frage starten</p>{step <= 4 ? <div className="flex items-center gap-2" aria-label={`Schritt ${step} von 4`}>{[1,2,3,4].map((n) => <span key={n} className={`h-2 rounded-full ${n === step ? "w-10 bg-cyan-500" : n < step ? "w-4 bg-cyan-300" : "w-4 bg-[rgb(var(--border))]"}`} />)}</div> : <span className="text-xs font-black uppercase tracking-[0.14em] text-cyan-600">Bereit</span>}</div>
    <div className="min-h-[32rem]">
      {step === 1 && <div><p className="text-sm font-semibold text-[rgb(var(--muted))]">Schritt 1 von 4</p><h1 className="mt-3 text-balance text-4xl font-black tracking-[-0.035em] sm:text-5xl">Was möchtest du herausfinden oder gemeinsam klären?</h1><p className="mt-4 text-base leading-7 text-[rgb(var(--muted))]">Ein Satz reicht – egal ob Entscheidung, Feedback, Leserfrage oder neue Idee.</p><textarea autoFocus value={question} onChange={(e) => setQuestion(e.target.value)} rows={3} placeholder="Zum Beispiel: Welchen Aspekt sollten wir als Nächstes genauer untersuchen?" className="mt-10 w-full resize-none border-0 border-b-2 border-[rgb(var(--border))] bg-transparent px-0 py-4 text-2xl font-bold outline-none focus:border-cyan-500"/><div className="mt-8 flex justify-end"><button disabled={!canContinueQuestion} onClick={() => setStep(2)} className={primary}>Weiter →</button></div></div>}
      {step === 2 && <div><p className="text-sm font-semibold text-[rgb(var(--muted))]">Schritt 2 von 4</p><h2 className="mt-3 text-4xl font-black tracking-[-0.035em] sm:text-5xl">Wie sollen Menschen antworten?</h2><p className="mt-4 text-base leading-7 text-[rgb(var(--muted))]">Du gibst Orientierung. Die Teilnehmenden können trotzdem ergänzen, was du noch nicht bedacht hast.</p><div className="mt-10 border-y border-[rgb(var(--border))]"><Choice selected={answerMode === "suggestions"} onClick={() => setAnswerMode("suggestions")} title="Auswahl + eigene Beiträge" body="Startoptionen wählen und zusätzlich Perspektiven, Ideen oder Alternativen ergänzen." badge="Empfohlen"/><Choice selected={answerMode === "fixed"} onClick={() => setAnswerMode("fixed")} title="Nur feste Antworten" body="Wenn deine Auswahl bereits vollständig und klar abgegrenzt ist."/></div><Nav back={() => setStep(1)} next={() => setStep(3)} nextLabel="Startantworten →" /></div>}
      {step === 3 && <div><p className="text-sm font-semibold text-[rgb(var(--muted))]">Schritt 3 von 4</p><h2 className="mt-3 text-4xl font-black tracking-[-0.035em] sm:text-5xl">Womit sollen Menschen anfangen?</h2><p className="mt-4 text-base leading-7 text-[rgb(var(--muted))]">Zwei Startoptionen reichen.</p><div className="mt-9 divide-y divide-[rgb(var(--border))] border-y border-[rgb(var(--border))]">{options.map((option,index) => <label key={index} className="flex items-center gap-4 py-4"><span className="w-7 text-xs font-black text-cyan-600">0{index+1}</span><input value={option} onChange={(e) => updateOption(index,e.target.value)} placeholder={`Startoption ${index+1}`} className="min-w-0 flex-1 bg-transparent py-2 text-lg font-bold outline-none"/></label>)}</div><button onClick={() => setOptions((current) => [...current,""])} className="mt-4 text-sm font-bold text-cyan-700">+ Startoption ergänzen</button><div className="mt-8 flex items-center justify-between"><button onClick={() => setStep(2)} className={back}>← Zurück</button><button disabled={!canFinish} onClick={() => setStep(4)} className={primary}>Weiter →</button></div></div>}
      {step === 4 && <div><p className="text-sm font-semibold text-[rgb(var(--muted))]">Schritt 4 von 4</p><h2 className="mt-3 text-balance text-4xl font-black tracking-[-0.035em] sm:text-5xl">Möchtest du Voxy nutzen?</h2><p className="mt-4 max-w-2xl text-base leading-7 text-[rgb(var(--muted))]">Wähle bewusst. Voxy ist optional und verändert nicht deine Kontrolle über Frage, Antworten oder Veröffentlichung.</p><div className="mt-10 border-y border-[rgb(var(--border))]"><Choice selected={voxyMode === "shared_intelligence"} onClick={() => setVoxyMode("shared_intelligence")} title="Mit Voxy – vorhandenes Wissen nutzen" body="Voxy kann dich künftig auf passende Erkenntnisse, Antwortideen oder offene Punkte aus anderen Befragungen hinweisen. Du entscheidest immer selbst, was du übernimmst."/><Choice selected={voxyMode === "manual_only"} onClick={() => setVoxyMode("manual_only")} title="Ohne Voxy – vollständig selbst bestimmen" body="Keine Hinweise aus anderen Befragungen. Du formulierst Frage und Antworten vollständig selbst."/></div><div className="mt-6 border-l-2 border-cyan-400 pl-5"><p className="text-sm font-black">eDebatte lernt gemeinsam – nicht persönlich.</p><p className="mt-1 text-sm leading-6 text-[rgb(var(--muted))]">Geeignete Ergebnisse verschiedener Befragungen sollen anonymisiert und zusammengefasst helfen, wiederkehrende Perspektiven und offene Punkte sichtbar zu machen. Daraus entstehen keine persönlichen Profile.</p><Link href="/datenschutz" className="mt-2 inline-block text-xs font-bold text-cyan-700 hover:underline dark:text-cyan-300">Mehr erfahren →</Link></div><div className="mt-8 flex items-center justify-between"><button onClick={() => setStep(3)} className={back}>← Zurück</button><button disabled={!voxyMode} onClick={finishVoxyChoice} className={primary}>Weiter zum Teilen →</button></div></div>}
      {step === 5 && <div><p className="text-sm font-semibold text-cyan-700 dark:text-cyan-300">Fertig.</p><h1 className="mt-3 text-4xl font-black tracking-[-0.04em] sm:text-5xl">Deine Frage ist bereit.</h1><p className="mt-4 text-base leading-7 text-[rgb(var(--muted))]">So können andere mitmachen. Zum Speichern und Teilen meldest du dich einmal an.</p><div className="mt-9 rounded-[2rem] bg-slate-950 p-6 text-white sm:p-8"><p className="text-xs font-black uppercase tracking-[0.18em] text-cyan-300">So können andere mitmachen</p><h2 className="mt-4 text-2xl font-black sm:text-3xl">{question}</h2><div className="mt-7 divide-y divide-white/15 border-y border-white/15">{visibleOptions.map((option,index) => <div key={`${option}-${index}`} className="flex justify-between gap-4 py-4"><span className="font-bold">{option}</span><span className="text-sm text-cyan-300">Auswählen →</span></div>)}</div></div><div className="mt-7 grid gap-5 rounded-[1.75rem] border border-cyan-500/30 bg-cyan-500/5 p-6 sm:grid-cols-[7rem_1fr] sm:items-center"><div className="flex h-24 w-24 items-center justify-center rounded-2xl border-2 border-dashed border-cyan-500 bg-white text-4xl" aria-hidden="true">⌗</div><div><p className="text-xs font-black uppercase tracking-[0.16em] text-cyan-700 dark:text-cyan-300">Link + QR-Code</p><h3 className="mt-1 text-xl font-black">Nach dem Anmelden kannst du teilen.</h3><p className="mt-2 text-sm leading-6 text-[rgb(var(--muted))]">Nach dem Speichern erhältst du den echten scanbaren Teilnahmecode und den Link zum Kopieren.</p><Link href={`/login?next=${encodeURIComponent(loginNext)}`} className="mt-4 inline-flex min-h-11 items-center rounded-full bg-cyan-500 px-5 py-2.5 text-sm font-black text-slate-950">Anmelden & teilen →</Link></div></div><div className="mt-7 flex flex-wrap items-center justify-between gap-4"><button onClick={() => setStep(1)} className={back}>Frage ändern</button><button onClick={openDetails} className={back}>Weitere Einstellungen →</button></div></div>}
    </div><p className="mt-5 text-center text-xs text-[rgb(var(--muted))]">Nichts wird automatisch veröffentlicht.</p>
  </section>;
}

function Choice({ selected, onClick, title, body, badge }: { selected:boolean; onClick:()=>void; title:string; body:string; badge?:string }) { return <button type="button" onClick={onClick} className="flex w-full items-start justify-between gap-5 border-b border-[rgb(var(--border))] py-6 text-left last:border-b-0"><div><div className="flex flex-wrap items-center gap-3"><span className="text-xl font-black">{title}</span>{badge && <span className="rounded-full bg-cyan-500 px-2.5 py-1 text-[10px] font-black uppercase text-slate-950">{badge}</span>}</div><p className="mt-2 max-w-xl text-sm leading-6 text-[rgb(var(--muted))]">{body}</p></div><span className={`mt-1 flex h-6 w-6 shrink-0 items-center justify-center rounded-full border-2 ${selected ? "border-cyan-500 bg-cyan-500 text-slate-950" : "border-[rgb(var(--border))]"}`}>{selected ? "✓" : ""}</span></button>; }
function Nav({ back, next, nextLabel }: { back:()=>void; next:()=>void; nextLabel:string }) { return <div className="mt-8 flex items-center justify-between"><button onClick={back} className="text-sm font-bold text-[rgb(var(--muted))]">← Zurück</button><button onClick={next} className="inline-flex min-h-13 items-center rounded-full bg-cyan-500 px-7 py-3 font-black text-slate-950">{nextLabel}</button></div>; }
