#!/usr/bin/env bash
set -euo pipefail

cat >&2 <<'MSG'
This legacy repair script is retired and intentionally performs no writes.

Reason:
- provider adapters are production-managed code and must not be regenerated by shell scripts;
- provider model defaults and retirement migrations are owned by features/ai/providerModelRegistry.ts;
- runtime selection is owned by features/ai/aiRuntimePolicy.ts;
- running the previous version could overwrite current adapters and reintroduce retired model IDs.

Use the normal repository workflow instead:
  pnpm -C apps/web run typecheck
  pnpm -C apps/web run ai:provider-smoke

For model routing configure AI_MODEL_ROUTING_MODE plus the documented provider model environment variables.
MSG

exit 2
